name: Update Changelog

on:
    push:
        branches:
            - main

jobs:
    update-changelog:
        runs-on: ubuntu-latest

        steps:
            - name: auto-update-changelog
              uses: MusfiqDehan/Auto-Update-CHANGELOG@v0.7.0
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
